name: CD - Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy"
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        env:
          TF_VAR_image_tag: ${{ github.event.inputs.image_tag }}
        run: terraform plan -var "image_tag=${{ github.event.inputs.image_tag }}"

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          TF_VAR_image_tag: ${{ github.event.inputs.image_tag }}
        run: terraform apply -auto-approve -var "image_tag=${{ github.event.inputs.image_tag }}"
